name: CI Pipeline for Spring Boot + Docker

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot Application
        run: mvn clean package --no-transfer-progress

      - name: Build Docker Image
        run: docker build -t project-task-management .

      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name springboot-container project-task-management

      - name: Wait and verify health endpoint
        run: |
          sleep 20
          curl --fail http://localhost:8080 || exit 1

      - name: Login to Docker Hub
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker Image
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker tag project-task-management $DOCKER_USERNAME/project-task-management
          docker push $DOCKER_USERNAME/project-task-management
